### ISSUE TITLE
Win32 installer reportet by windows10 as virus

### ISSUE THREAD

**Issue by Caberhagen** [linX-project/linX#2]
Windows 10 removes linX from system with this alert:
Trojan:Win32/Tilken.B!cl

**Comment by danlinx** [comment]
This is a false positive thrown by pyminer (internal mining application in the wallet). It will be removed in the next release as it's no longer relevant. It's completely safe to dismiss this warning though.

**Comment by danlinx** [comment]
You can read more about it at the following link. https://github.com/nicehash/NiceHashMinerLegacy/issues/338

**Comment by Caberhagen** [comment]
Thanks for your answer. So now it's clear for me.
CU
