### ISSUE TITLE
Pubkey for dev fee address

### ISSUE THREAD

**Issue by kr1z1s** [linX-project/linX#6]
Hello!

I kr1z1s - https://github.com/kr1z1s

I create p2pool LinX https://github.com/kr1z1s/p2pool-linx

Example node - http://p2p-spb.xyz:2924/static/

Help me please. I want upgrade p2pool to last release LinX

I need pubkey for dev fee address. PUBKEY )) not private 

Thank you

**Comment by linX-project** [comment]
Hi kr1z1s,

Great!

It's right there in the config file : 

https://github.com/linX-project/linx-unomp-pool-settings/blob/master/linx.json.example#L15

You just have to ensure that it is the first payout in the array or you will receive rejected blocks once the dev fee starts.

If you have any other questions just ask.

Thanks for supporting the project!

**Comment by kr1z1s** [comment]
No no no

You fee address - XF7kCcs4woQD9WWnCHuN6SWPeUNK2fBspr

I need pubkey for this address

Example

`linXd validateaddress XPUVAWD3bm7Eqx7PwwVPMpwVmyzBueAs9G
{
    "isvalid" : true,
    "address" : "XPUVAWD3bm7Eqx7PwwVPMpwVmyzBueAs9G",
    "ismine" : true,
    "isscript" : false,
    "pubkey" : "0358bffde1f44aa783a9f9109459a045a98e75ca374b7636f31ff6e90eb9a43c4a",
    "iscompressed" : true,
    "account" : ""
}
`
Give me this string for ypu address 
  "pubkey" : "0358bffde1f44aa783a9f9109459a045a98e75ca374b7636f31ff6e90eb9a43c4a"

**Comment by linX-project** [comment]
Ahh sorry, sure can you just email us at contact@mylinx.io
